🛣 routes: create inbound inventory movement route
CtrI-Alt-Del/stocker pull request #40
Opened 2024-09-18 15:28 UTC by Tico1606

2024-09-18 20:39 UTC, JohnPetros requested changes

2024-09-18 20:39 UTC, JohnPetros commented on apps/server/src/app/fastify/routes/inbound-inventory-movement-routes.ts
> +  app.post('/', async (request, response) => {
the correct route is `/inbound`

2024-09-18 20:46 UTC, kaufon commented
é o bananinha

2024-09-19 10:27 UTC, merged

2024-09-20 19:41 UTC, kaufon commented
ta faltando propriedade cara