Notfound
CtrI-Alt-Del/stocker pull request #67
Opened 2024-09-26 10:56 UTC by FaelSantoss

2024-09-28 18:38 UTC, JohnPetros requested changes

2024-09-28 18:38 UTC, JohnPetros commented on apps/web/src/ui/components/pages/notfound/index.tsx
> +          <Link href="/" passHref>
Using a button inside a link is a bad practice. Instead , use the `as` prop of Button component from NextUi to use it as a Link component, as it is documented [here](https://nextui.org/docs/components/link#polymorphic-component).

2024-09-29 15:34 UTC, 0thigs approved these changes

2024-09-29 15:34 UTC, 0thigs commented
I will correct it!

2024-09-29 15:34 UTC, 0thigs approved these changes

2024-09-29 15:57 UTC, closed without merging